name: Run CheckPage Every 15 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # runs every 15 mins
  workflow_dispatch:       # allows manual trigger too

jobs:
  run-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run checkPage
        run: node runCron.js  # or whatever file calls checkPage()
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
