name: Run CheckPage Every 15 Minutes

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 mins
  workflow_dispatch:       # Allow manual trigger

jobs:
  run-check-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run checkPage script
        run: node runCron.js  # or node checkPage.js
